### ISSUE TITLE
Large generated code size, long compilation time

### ISSUE THREAD

**Issue by bruce** [plataformatec/nimble_parsec#16]
Over the last week or so I've been experimenting with using nimble_parsec as the basis for a new GraphQL parser for the [absinthe](https://github.com/absinthe-graphql) project.

What I've built so far is here: https://github.com/bruce/absinthe/blob/nimble-parsec-experiment/lib/absinthe/parser.ex 

At this point I have the rough (and probably very naive) implementation of (almost) the entire GraphQL specification built out as nimble_parsec combinators. The experience has been great; I've really enjoyed using the package and feel like this is working towards much more maintainable, enjoyable parser code than our current leex/yecc implementation.

I've gotten it to the point that it compiles, although it doesn't actually do a whole lot yet (I'm, for example, only using map/traverse in a few places to generate a few of the resulting structs we'll want eventually, and I'm not skipping ignored input in most of the combinators yet). I've exposed a few `defparsec`s for a few tests (and some necessary recursion), and it's feeling pretty good.

Except for the compile time (a few minutes on my new XPS 13) and the size of the resulting `.beam`, which is... 23MB. (Reducing the `defparsec` usage to those strictly needed for recursion and the main entry point reduces the `.beam` filesize to 22MB.)

It's quite possible that I'm doing something boneheaded with the way this is structured/built at this point, but on the off chance I'm not [completely] and this can help serve as a sample of a larger grammar to track down an issue (with generation or documentation), I'd love it if someone could take a peek at what [I've built so far](https://github.com/bruce/absinthe/blob/nimble-parsec-experiment/lib/absinthe/parser.ex).

```
$ elixir --version
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.4 (compiled with OTP 20)
```

**Comment by michalmuskala** [comment]
Taking a quick look, one thing that jumps at me is the use of `skip_ignored`. This is a complex combinator that is applied repeatedly in many places - this means that in each place, the entire combinator has to be compiled. Assigning a combinator to a variable and using it multiple times means it will be compiled multiple times and inlined at each use - which can be expensive for large combinators.

**Comment by bruce** [comment]
@michalmuskala What's the right way to do something like that? Use `defparsec/2` and `parsec/1`? Should I just do that with all the grammar entities? For some reason that felt like it would create _more_ code rather than less (but, I've been very lax in my reading of the actual implementation).

**Comment by bruce** [comment]
Definitely on the right track; removing `skip_ignored` entirely, down to 8.7M. Going to try using `defparsec` instead now (I do need to skip those chars, of course). Will report that as well.

**Comment by bruce** [comment]
9.8M adding back in `skip_ignored`, but converting it to `defparsec/2` and `parsec/1`. I'll try this with the rest of the grammar and see how things change.

(FWIW, having small combinators to test externally and use as utilities is a win anyway.)

**Comment by michalmuskala** [comment]
Yes, using `defparsec` and `parsec` for commonly repeating things should decrease the code size - the parser will be compiled just once.

**Comment by bruce** [comment]
Thanks @michalmuskala. After a few changes to commonly used combinators, I'm already at < 1MB. Closing this issue while I continue to improve things. I'll try to put in a PR down later to improve the docs regarding trade-offs on inlining vs `defparsec`.

**Comment by josevalim** [comment]
This looks great @bruce! Probably the biggest grammar written with NimbleParsec so far. I would love to see how it compares speed-wise with the `xrl+yrc` parser, especially because NimbleParsec doesn't require converting to a list, which should make it use less memory too.

Regarding compilation times, I have played a bit with your fork and it seems the time to compile .xrl+.yrl to beam versus nimble_parsec to beam is roughly the same right now. The .beam size of a nimble_parsec is a bit bigger though (250k vs 330k), so you did a great work on abstracting the repeated pieces with `defparsec+parsec`.
