### ISSUE TITLE
between and sep_by combinators

### ISSUE THREAD

**Issue by mbuhot** [plataformatec/nimble_parsec#17]
[Parsec](https://hackage.haskell.org/package/parsec-3.1.13.0/docs/Text-Parsec-Combinator.html) has some handy combinators [between](https://hackage.haskell.org/package/parsec-3.1.13.0/docs/src/Text.Parsec.Combinator.html#between) and [sepBy](https://hackage.haskell.org/package/parsec-3.1.13.0/docs/src/Text.Parsec.Combinator.html#sepBy).

Having these in the package should make it easy to parse bracketed / delimited text, eg:

```elixir
array_of_ints = between(string("["), string("]"), sep_by(",",  integer()))
```
or perhaps with the order of arguments reversed:

```elixir
array_of_ints = 
  integer()
  |> sep_by(",")
  |> between(string("["), string("]"))
```

**Comment by josevalim** [comment]
`between` can be implemented with concat and I believe `sep_by` can be implemented with `repeat_while`. So I would prefer to keep the core `nimble` for now rather than adding many convenience functions. :)

**Comment by mbuhot** [comment]
Yes they're pretty simple:

```elixir
  def sep_by(element, separator) do
    sep_by_tail = repeat(ignore(separator) |> concat(element))
    non_empty = concat(element, sep_by_tail)
    choice([non_empty, empty()])
  end

  def between(body, open, close) do
    ignore(open)
    |> concat(body)
    |> concat(ignore(close))
  end
```

**Comment by josevalim** [comment]
Beautiful. Thanks for the examples, they will help guide anyway that may need this feature too!
