### ISSUE TITLE
Common Combinators

### ISSUE THREAD

**Issue by zachdaniel** [plataformatec/nimble_parsec#18]
Many parser combinator libraries maintain a set of the common combinators, like `whitespace` and `word`. Would you accept pull requests to add those kinds of combinators? Usually they are organized by some kind of domain, like `NimbleParsec.Text` and `NimbleParsec.Number`.

**Comment by josevalim** [comment]
@zachdaniel not right now. I prefer to keep the core small, *cough* nimble *cough*, and let people build their own. :)
