### ISSUE TITLE
Parsing "123" as integer

### ISSUE THREAD

**Issue by meox** [plataformatec/nimble_parsec#19]
I've defined a parser in this way:
```
int_t = integer(min: 1) |> tag(:int_t)
defparsec :parse_inttype, int_t
```

When I try to use it in this way:
```
RuleC.parse_inttype("123")
```
I get this:
```
{:ok, [int_t: '{'], "", %{}, {1, 0}, 3}
```
instead of:
```
{:ok, [int_t: 123], "", %{}, {1, 0}, 3}
```

But other case works:
```
> RuleC.parse_inttype("213")
{:ok, [int_t: [213]], "", %{}, {1, 0}, 3}
```

I'm not an Elixir expert but seems that the internal type of **integer** is a char instead of int

**Comment by josevalim** [comment]
The parser returns a list of tokens. In this case, you have the list `[123]` which is treated as a list of characters and printed as '{'`. You want to use `unwrap_and_tag`. :)

**Comment by meox** [comment]
Thanks @josevalim I checked it but in 0.2.2 is not present.
Could you release a 0.2.3 with that one?

**Comment by meox** [comment]
I take it directly from github and it's working.
Thanks for the suggestion.

**Comment by josevalim** [comment]
0.3.0 released!
