### ISSUE TITLE
forwad declaration of parser

### ISSUE THREAD

**Issue by meox** [plataformatec/nimble_parsec#20]
Readind the doc:
https://github.com/plataformatec/nimble_parsec/blob/8005d1439e2479dcbcc13cb8c7bbd0fb833af875/lib/nimble_parsec.ex#L36

seems not possible to call "normal" function from **defparsec**.
Following the suggstion of the doc I started using module variable but this seems to be limited.
For example I'm not able to rapresent mutal recursive parser, somenthing like:

```
    lambda_t =
      ignore(string("fn"))
      |> ignore(ascii_char([?(]))
      |> concat(optional(
        symbol
        |> repeat(
          |> ignore(ascii_char([?,]))
          |> concat(symbol)
          )
        |> tag(:parameters)
      ))
      |> ignore(ascii_char([?)]))
      |> ignore(ascii_char([?{]))
      |> concat(
          statements
          |> tag(:body)
      )
      |> ignore(ascii_char([?}]))
      |> tag(:lambda_t)

    statements = choice ([basic_types, lambda_t]) ...
```
**statements** could contains a **lambda_t** and in order to use it we should declare before lambda_t, so this approach is not easy to follow.

Any idea how to achive this?

Any suggestion?

**Comment by josevalim** [comment]
For recursion, you need to new intermediate parsers with defparsec and use
the parsec combinator to invoke them.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by meox** [comment]
could you explain it with a very simple exaple?
thanks a lot

**Comment by josevalim** [comment]
Not at the computer right now. Please see the docs for a function named
parsec or the tests.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
I just noticed the docs for it aren’t good :( see the examples/simple_xml
or tests. I will push better examples later. :)
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
I have pushed a smaller simple_xml example to the parsec docs: https://hexdocs.pm/nimble_parsec/NimbleParsec.html#parsec/2
