### ISSUE TITLE
Introduce eof combinator

### ISSUE THREAD

**Issue by josevalim** [plataformatec/nimble_parsec#26]
So we don't need to explicitly check that we are done every time.

**Comment by aerosol** [comment]
@josevalim Hi, interested in giving it a go. Would you mind pasting some code to illustrate the issue?

**Comment by josevalim** [comment]
@aerosol today we need to write code like this at the end of parsing:

https://github.com/plataformatec/nimble_parsec/blob/9da0526a5ee6b7245e9a4cf95e8149e076e0c543/examples/simple_xml.exs#L20-L21

If we introduce a combinator, we could do it automatically. We could say that we expected the end of a file but there was some leftover.

**Comment by aerosol** [comment]
Sorry I didn't pull that one off :(
