### ISSUE TITLE
Introduce Regex combinator

### ISSUE THREAD

**Issue by imetallica** [plataformatec/nimble_parsec#31]
Hi everyone,

The idea of having a regex combinator is to be easier to implement some rules that makes sense to be implemented via Regex, such as the names of XML elements, which have strict rules for naming.

As an example, Scala has a Regex parser, which makes parsing names of XML elements as easy as `[a-zA-Z_:][a-zA-Z0-9\.-_:]*`.

I'm not sure if it's viable to implement these, since we cannot do pattern matching on regexes on BEAM, but I think this can be worthwile to consider.

**Comment by josevalim** [comment]
Using regexes would defeat the point of `nimble_parsec` which is to provide performant parsing. We could have our regex parser, but given that one of the goals of `nimble_parsec` is to stay nimble, a Regex compiler is definitely too much. Somebody could build something on top of `nimble_parsec` though.
