### ISSUE TITLE
defparsec should define the main function first

### ISSUE THREAD

**Issue by tmbb** [plataformatec/nimble_parsec#34]
Currently, if I have something like this:

```elixir
  @impl Makeup.Lexer
  defparsec :root,
    root_combinator
```

I get this:

```plaintext
warning: function root__0/6 is private, @impl attribute is always discarded for private functions/macros
  test/lexer/fixtures/token_lexer.exs:31
```

It looks like this happens because nimble_parsec doesn't generate the `def root(...)` clause first, generating some helper function clauses instead. This makes it hard to annotate the function with docs or `@impl` attributes.

**Comment by josevalim** [comment]
Good catch. Can you please send a PR or something?

**Comment by tmbb** [comment]
I'll try, but as you know, the parsec compiler is not exactly simple to understand for an outsider. I'll send a PR as soon as I can.
