### ISSUE TITLE
"Position" has changed, but generated documentation was not changed?

### ISSUE THREAD

**Issue by schnittchen** [plataformatec/nimble_parsec#36]
The generated doc for an entry point states

```
Returns {:ok, [token], rest, context, line, byte_offset} or {:error, reason,
rest, context, line, byte_offset}.
```

which is not correct because at the position of `line` I see a tuple. I suspect it is {line where accumulared result begins, col where it begins}?

**Comment by josevalim** [comment]
Yes. Can you please send a PR? It is line and column relative to that line.
