### ISSUE TITLE
Syntax abuse

### ISSUE THREAD

**Issue by roehst** [plataformatec/nimble_parsec#38]
Hi, I played a bit with quoting and the following code parses just fine using Code.string_to_quoted:

>       parser parseName do
>         many1 letter
>       end
> 
>       parser parseAbs do
>         string "abs"
>         spaces
>         name <- parseName
>         spaces
>         body <- parseTerm
>         return {:abs, name, body}
>       end
> 
>       parser parseTerm do
>         chainl1 (try(parseAbs) or parseVar or parens(parseTerm)), parseApp
>       end
> 
>       parser parseVar do
>         name <- parseName
>         return {:var, name}
>       end
> 
>       parser parens p do
>         char '('
>         p_ <- p
>         char ')'
>         return p_
>       end
> 
>       parser parseApp do
>         spaces
>         return (fn f, a -> {:app, f, a} end)
>       end

Which looks basically the same as using Parsec in Haskell. Not suggesting anything, just wanted to share.

**Comment by josevalim** [comment]
Thanks! Maybe someone interested in this approach can tackle it in a separate project!
