### ISSUE TITLE
Add `ok` and `error` records for matching on the parser result

### ISSUE THREAD

**Issue by josevalim** [plataformatec/nimble_parsec#4]

**Comment by josevalim** [comment]
Actually, we are not adding this, because the API you export from your parser to users is up to you and I am afraid this will cause people to rely on NimbleParsec indirectly.

Also, it is very likely that we won't change the ok/error responses. Maybe to return the userdata but I don't think that would be necessary either because the algorithm is tail recursive so we are never matching on ok results. Except when we call another parsec but i don't think the contexts and stacks should leak then.

**Comment by tmbb** [comment]
> Actually, we are not adding this, because the API you export from your parser to users is up to you and I am afraid this will cause people to rely on NimbleParsec indirectly.

You're exposing the relevant parts of the tuple to the `traverse` function, so, for now, I agree you don't need to expose anything else. The way this works now, the user won't have to match on the tuple directly, so there is no need to provide records.
