### ISSUE TITLE
Minor usability issue with repeat and optional?

### ISSUE THREAD

**Issue by atamis** [plataformatec/nimble_parsec#41]
Hey, I ran into this issue while writing a language parser in `nimble_parsec`. The issue was that chaining the repeat and optional combinators like so: `repeat(optional(...))` never terminates execution. The reason is pretty clear: it repeatedly chooses the "None" option of `optional`, and just keeps going. A full replication of the issue can be found [in this gist](https://gist.github.com/atamis/6e8fa93d69a07a6bce8035cf6d9b0a21).

The symptoms of this bug are that the combinator never terminates, so as long as the user does rudimentary testing of the parser, they will identify the issue. It never terminates on any input, including inputs which can never match. Although I identified the issue quickly, a newer user might have real trouble with it. I somewhat doubt this error can be detected statically, but a warning in the docs might help save some people some time when they encounter this issue.

**Comment by josevalim** [comment]
yes, definitely. Can you please send a PR? We already have similar warnings
on repeat/2 docs.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by atamis** [comment]
Thanks. How does this wording sound?

**Comment by josevalim** [comment]
@atamis beautiful! :heart:
