### ISSUE TITLE
Remove compiler warnings from nimble_parsec.compile

### ISSUE THREAD

**Issue by kipcole9** [plataformatec/nimble_parsec#48]
`mix nimble_parsec.compile` is great for removing `nimble_parsec` as a dependency for a package (as is currently the case for [ex_cldr](https://hex.pm/packages/ex_cldr)).  However compiling the resultant code can produce a *lot* of compiler `unused variable` warnings which I think is not a good thing for a package if it can be avoided.

I have explored a little and can remove many of the warnings by replacing in `NimbleParsec.Compiler`:
```
  defp build_proxy_to(name, next, n) do
    args = quote(do: [rest, acc, stack, context, line, offset])
    [_, acc, stack, _, _, _] = args

    body =
      quote do
        unquote(build_acc_depth(n, acc, stack)) = stack
        unquote(next)(rest, acc, stack, context, line, offset)
      end

    {name, args, true, body}
  end
```
with
```
  defp build_proxy_to(name, next, n) do
    args = quote(do: [rest, acc, stack, context, line, offset])
    [_, acc, stack, _, _, _] = args

    body =
      quote do
        # Is removed in a compiler optimisation pass
        _ = {acc, stack}

        unquote(build_acc_depth(n, acc, stack)) = stack
        unquote(next)(rest, acc, stack, context, line, offset)
      end

    {name, args, true, body}
  end
```
However there are still one case I haven't nailed down yet which produces repeated:
```
warning: variable "context" is unused
  lib/cldr/language_tag/rfc5646_parser.ex:4116

warning: variable "line" is unused
  lib/cldr/language_tag/rfc5646_parser.ex:4116

warning: variable "offset" is unused
  lib/cldr/language_tag/rfc5646_parser.ex:4116

warning: variable "rest" is unused
  lib/cldr/language_tag/rfc5646_parser.ex:4116
```
These warnings come from code generated with the following shape:
```
  defp language_tag__35(
         inner_rest,
         inner_acc,
         [{rest, acc, context, line, offset} | stack],
         inner_context,
         inner_line,
         inner_offset
       ) do
    language_tag__27(
      inner_rest,
      [],
      [{inner_rest, inner_acc ++ acc, inner_context, inner_line, inner_offset} | stack],
      inner_context,
      inner_line,
      inner_offset
    )
  end
```

I am happy to make a PR for this, but could also use some guidance on where to hunt down this last case since the pattern `[{rest, acc, context, line, offset} | stack]` is used in 5 places for different combinator compilations.

**Comment by josevalim** [comment]
Hi @kipcole9! Please do send a PR and I can work on the remaining cases if you send me a link to a repository + commit that reproduces the remaining ones. :)

**Comment by kipcole9** [comment]
Thanks @josevalim, [PR submitted](https://github.com/plataformatec/nimble_parsec/pull/49) with notes on how to reproduce the remaining warnings.
