### ISSUE TITLE
Error is not returned when  `parsec`/`repeat` is used

### ISSUE THREAD

**Issue by arathunku** [plataformatec/nimble_parsec#55]
Hello,

I've been recently working on parsing https://projectfluent.org/ (detail, failing spec in description). I'm trying to improve error messages and add more validations but I'm stuggling with returning errors.

Failing spec:
```elixir
  describe "errors from combinators" do
    defcombinatorp(:errors,
      empty()
      |> post_traverse(:set_error)
    )

    defcombinatorp(:function_reference,
      repeat(
        empty()
        |> parsec(:errors)
      )
    )

    defparsec :parse_function_reference, parsec(:function_reference)

    defp set_error(_rest, _, _context, _line, _offset) do
      {:error, "something wrong"}
    end

    test "returns ok/error" do
      assert parse_function_reference("") == {:error, "something wrong", "", %{}, {1, 0}, 0}
    end
  end
```

```
  1) test errors from combinators returns ok/error (NimbleParsec.IntegrationTest)
     test/integration_test.exs:121
     Assertion with == failed
     code:  assert parse_function_reference("") == {:error, "something wrong", "", %{}, {1, 0}, 0}
     left:  {:ok, [], "", %{}, {1, 0}, 0}
     right: {:error, "something wrong", "", %{}, {1, 0}, 0}
     stacktrace:
       test/integration_test.exs:122: (test)
```

It will pass if I either:

  1. Remove `repeat` in `function_reference`

or

  1. Switch `parsec(:errors)` to `post_traverse(:set_error)`.

Is there any way to deal with that and ensure that errors are returned or is this expected behavior that I can deal with somehow differently? Of course, my combinators are more complex than this example.

Thank you for any help.

**Comment by josevalim** [comment]
I believe this is working as intended because repeat is 0, 1 or many matches. You can use `times` if you want to at least one occurrence. Also, keep in mind we recommend not relying on `parsec` that much. But I assume in your project they are wrapping quite big chunks. :)

**Comment by arathunku** [comment]
That's exactly what's happening. Thank you @josevalim.
