### ISSUE TITLE
Customize doc of generated function?

### ISSUE THREAD

**Issue by inklesspen** [plataformatec/nimble_parsec#56]
I'd like to customize the doc of the entry function generated by `defparsec`, so I can include some examples of things it can and cannot parse. Is there a way to do this?

**Comment by josevalim** [comment]
Hi @inklesspen! You can define a `@doc` clause before defparsec:

```
@doc "mydoc"
defparsec ...
```

We only use the default docs if none are provided. Also make sure you are on latest, as this feature was added at some point down the road.

**Comment by inklesspen** [comment]
Yeah, turned out I was on 0.4.0 for some reason. Thanks!
