### ISSUE TITLE
Feature: unmatchable combinator

### ISSUE THREAD

**Issue by liamwhite** [plataformatec/nimble_parsec#61]
Rationale: the choice combinator currently accepts a list of two or more combinators. However, when writing a macro that can accept a variable number of choices, it is useful to have a combinator that never matches to handle the case of zero choices provided.

See here for a practical example:
https://github.com/derpibooru/philomena/blob/c66fe0ca39cd8d4f51b21c8fe939489c24bba892/lib/philomena/search/lexer.ex#L262-L285

**Comment by josevalim** [comment]
Hi @liamwhite!

You can do that today with [a post_traverse function](https://hexdocs.pm/nimble_parsec/NimbleParsec.html#post_traverse/3) that returns `{:error, reason}` but we should probably make it more accessible.

@tmbb I think you proposed a `error(combinator, reason)` combinator some time ago, correct?

**Comment by josevalim** [comment]
Due to the lack of replies, I will close this for now. Feedback is always welcome.
