### ISSUE TITLE
Undefined function defparsec/1

### ISSUE THREAD

**Issue by daviwesley** [plataformatec/nimble_parsec#63]
I created a project using the `mix new project` and add the dependency in `mix.exs`, I found this example in documentation
```elixir
defmodule MyParser do
  import NimbleParsec

  defparsec integer(min: 1) |> tag(:integer)
end
MyParser.integer("1234")
```
when I run this example from project directory using the  `iex -S mix` I got this error message
`** (CompileError) iex:12: undefined function defparsec/1`

Elixir 1.9.1
NimbleParser 0.5.1

**Comment by wojtekmach** [comment]
there's `defparsec/1` but there's `defparsec/2,3`; you need to give a name to your parsec:

```elixir
defparsec :my_int, integer(min: 1) |> tag(:integer)
```

**Comment by wojtekmach** [comment]
Oh, the documentation is wrong indeed in a couple places, I'll fix it up. Thanks for the report!
