### ISSUE TITLE
feature: possibly empty sequence of iterations of A

### ISSUE THREAD

**Issue by terriblecodebutwork** [plataformatec/nimble_parsec#65]
Hi, 

the helper function that match possibly empty sequence of iterations of
a combinator will be useful. I wrote a simple implementation.

```ex
defmodule LexerHelper do
  import NimbleParsec

  def possible(comb, to_poss) do
    comb
    |> repeat(to_poss)
    |> lookahead_not(to_poss)
  end
end
```

```ex
digit = ascii_char [?0..?9]
num = digit
    |> possible(
      concat(
        optional(ascii_char([?_])),
        digit
      )
    )
defparsec :num, num
```

```iex
iex(1)> Lexer.num "123"
{:ok, '123', "", %{}, {1, 0}, 3}
iex(2)> Lexer.num "123_234"
{:ok, '123_234', "", %{}, {1, 0}, 7}
iex(3)> Lexer.num "123_234_"
{:ok, '123_234', "_", %{}, {1, 0}, 7}
iex(4)> Lexer.num "123_234 34"
{:ok, '123_234', " 34", %{}, {1, 0}, 7}
```

**Comment by josevalim** [comment]
Thanks! How is `possible` different from `optional`? If you have a working implementation, can you please share the code? Thank you!

**Comment by terriblecodebutwork** [comment]
@josevalim  The implementation is above. `optional` only matchs once or none, `possible` will matchs any times or none.

**Comment by josevalim** [comment]
Oh, sorry. Somehow I missed it. :D

If you can implement `possible` today, then that's our recommendation. We don't want to add a bunch of built-in helpers to NimbleParsec, as our hope is to keep it small, only with the necessary combinators.

Tjhank you!
