### ISSUE TITLE
The call ... does not have an opaque term of type 'Elixir.NimbleParsec':t() as 1st argument

### ISSUE THREAD

**Issue by rlipscombe** [plataformatec/nimble_parsec#66]
I don't know if this is a nimble_parsec bug, or an Elixir bug, or a Dialyzer bug, or just me doing something wrong, but here goes:

I'm playing with NimbleParsec, and I'm attempting to put something together that recognises boolean algebra. At the moment, I'm simply trying to get it to recognise two booleans catenated, and I've come up with this:

```
defmodule Exlox.Parser.Boolean do
  import NimbleParsec

  def boolean(combinator \\ empty()) do
    true_p = string("true") |> replace(true)
    false_p = string("false") |> replace(false)

    choice(combinator, [true_p, false_p])
  end
end

defmodule Exlox.Parser do
  import NimbleParsec
  import Exlox.Parser.Boolean

  defparsec :expression, boolean() |> boolean()
end
```

That is: it recognises "truefalse", "truetrue", "falsefalse" and "falsetrue". This is OK (though I wonder whether this is the best way to do this...).

But dialyzer doesn't like it:

```
lib/parser.ex:4: The call 'Elixir.Exlox.Parser.Boolean':boolean([]) does not have an opaque term of type 'Elixir.NimbleParsec':t() as 1st argument
```

What am I doing wrong?

**Comment by josevalim** [comment]
Hi! Which NimbleParsec version are you using?
-- 


*José Valim*
www.plataformatec.com.br
Founder and Director of R&D

**Comment by rlipscombe** [comment]
```
{:nimble_parsec, "~> 0.5.2"}
```

**Comment by josevalim** [comment]
So it is most likely a wrong Dialyzer specification from us. If you can push a project that reproduces it, we can take a look at the specs.

**Comment by rlipscombe** [comment]
https://github.com/rlipscombe/nimble_parsec_experiments/tree/nimble_parsec-issue-66

**Comment by rlipscombe** [comment]
You can replicate it with `make dialyzer` in the above project, or by loading it into VS Code (with appropriate extensions) and waiting for ElixirLS to complain.
